// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3546.subsystems;

import org.usfirst.frc3546.RobotMap;
import org.usfirst.frc3546.commands.*;
import edu.wpi.first.wpilibj.PowerDistributionPanel;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class PowerDistribution extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final PowerDistributionPanel powerDistributionPanel = RobotMap.powerDistributionPowerDistributionPanel;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new ReportCurrent());

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    public String getWinchCurrentDrawString(){
        double current1 = powerDistributionPanel.getCurrent(0);
        double current2 = powerDistributionPanel.getCurrent(15);

        return "1: " + current1 + " Amps. 2: " + current2 + " Amps. T: " + (current1 + current2) + " Amps.";
    }

    public String getWinchCurrentDrawStringLong(){
        double current1 = powerDistributionPanel.getCurrent(0);
        double current2 = powerDistributionPanel.getCurrent(15);

        return "Winch Motor 1 is drawing: " + current1
                + " Amps. Winch Motor 2 is drawing: " + current2
                + " Amps. This makes a total of " + (current1 + current2) + " Amps.";
    }
}

